categories/urls.py
from django.urls import path
#following line is for the function based view
from . import views
#following line is for the class based view
from .views import CategoryList, CompanyList, CompanyCreateView, CompanyDetailView, CompanyUpdateView,CompanyDeleteView, ProductCreateView, AboutView, AboutUsView
from django_filters.views import FilterView
from .filters import CompanyFilter

urlpatterns = [
    #the following path is for the test only
    path('getip', views.get_ip, name = 'home'),
    path('', CategoryList.as_view(), name = 'category_list'),
    path('create/', CompanyCreateView.as_view(), name = 'company_create'),
    path('<str:category>/<int:pk>/', CompanyDetailView.as_view(), name = 'company_detail'),
    path('<int:pk>/delete/', CompanyDeleteView.as_view(), name = 'company_delete'),
    path('<int:pk>/update/', CompanyUpdateView.as_view(), name = 'company_update'),
    path('search/', FilterView.as_view(filterset_class=CompanyFilter, 
        template_name ='categories/company_search.html'), name='search'),
    path('<int:pk>/product/', ProductCreateView.as_view(), name = 'product_new'),
    path('about/', AboutView.as_view(), name = 'aboutknowhere'),
    path('aboutus/', AboutUsView.as_view(), name = 'aboutus'),
    # why should be this \
    # because create is taken as the string value for the category
    path('<str:category>/', views.CompanyList.as_view(), name='company_list'),
    
    
]

knowhere/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('categories/', include('categories.urls')),
    path('comments/', include('django_comments.urls')),
    path('chat/',include('postman.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postman/postman/urls.py
"""
If the default usage of the views suits you, simply use a line like
this one in your root URLconf to set up the default URLs::

    (r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),

Otherwise you may customize the behavior by passing extra parameters.

Recipients Max
--------------
Views supporting the parameter are: ``WriteView``, ``ReplyView``.
Example::
    ...View.as_view(max=3), name='write'),
See also the ``POSTMAN_DISALLOW_MULTIRECIPIENTS`` setting

User filter
-----------
Views supporting a user filter are: ``WriteView``, ``ReplyView``.
Example::
    def my_user_filter(user):
        if user.get_profile().is_absent:
            return "is away"
        return None
    ...
    ...View.as_view(user_filter=my_user_filter), name='write'),

function interface:
In: a User instance
Out: None, False, '', 'a reason', or ValidationError

Exchange filter
---------------
Views supporting an exchange filter are: ``WriteView``, ``ReplyView``.
Example::
    def my_exchange_filter(sender, recipient, recipients_list):
        if recipient.relationships.exists(sender, RelationshipStatus.objects.blocking()):
            return "has blacklisted you"
        return None
    ...
    ...View.as_view(exchange_filter=my_exchange_filter), name='write'),

function interface:
In:
    ``sender``: a User instance
    ``recipient``: a User instance
    ``recipients_list``: the full list of recipients or None
Out: None, False, '', 'a reason', or ValidationError

Auto-complete field
-------------------
Views supporting an auto-complete parameter are: ``WriteView``, ``ReplyView``.
Examples::
    ...View.as_view(autocomplete_channels=(None,'anonymous_ac')), name='write'),
    ...View.as_view(autocomplete_channels='write_ac'), name='write'),
    ...View.as_view(autocomplete_channel='reply_ac'), name='reply'),

Auto moderators
---------------
Views supporting an ``auto-moderators`` parameter are: ``WriteView``, ``ReplyView``.
Example::
    def mod1(message):
        # ...
        return None
    def mod2(message):
        # ...
        return None
    mod2.default_reason = 'mod2 default reason'
    ...
    ...View.as_view(auto_moderators=(mod1, mod2)), name='write'),
    ...View.as_view(auto_moderators=mod1), name='reply'),

function interface:
In: ``message``: a Message instance
Out: rating or (rating, "reason")
    with reting: None, 0 or False, 100 or True, 1..99

Others
------
Refer to documentation.
    ...View.as_view(form_classes=(MyCustomWriteForm, MyCustomAnonymousWriteForm)), name='write'),
    ...View.as_view(form_class=MyCustomFullReplyForm), name='reply'),
    ...View.as_view(form_class=MyCustomQuickReplyForm), name='view'),
    ...View.as_view(template_name='my_custom_view.html'), name='view'),
    ...View.as_view(success_url='postman:inbox'), name='reply'),
    ...View.as_view(formatters=(format_subject, format_body)), name='reply'),
    ...View.as_view(formatters=(format_subject, format_body)), name='view'),

"""
from __future__ import unicode_literals

from django import VERSION
from django.conf import settings
from django.conf.urls import url
if VERSION < (1, 10):
    from django.core.urlresolvers import reverse_lazy
else:
    from django.urls import reverse_lazy
if getattr(settings, 'POSTMAN_I18N_URLS', False):
    from django.utils.translation import pgettext_lazy
else:
    def pgettext_lazy(c, m): return m
from django.views.generic.base import RedirectView

from .views import (InboxView, SentView, ArchivesView, TrashView,
        WriteView, ReplyView, MessageView, ConversationView,
        ArchiveView, DeleteView, UndeleteView, MarkReadView, MarkUnreadView)

app_name = 'postman'
urlpatterns = [
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^inbox/(?:(?P<option>m)/)?$'), InboxView.as_view(), name='inbox'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^sent/(?:(?P<option>m)/)?$'), SentView.as_view(), name='sent'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^archives/(?:(?P<option>m)/)?$'), ArchivesView.as_view(), name='archives'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^trash/(?:(?P<option>m)/)?$'), TrashView.as_view(), name='trash'),
    url(pgettext_lazy('postman_url', r'^write/(?:(?P<recipients>[^/#]+)/)?$'), WriteView.as_view(), name='write'),
    url(pgettext_lazy('postman_url', r'^reply/(?P<message_id>[\d]+)/$'), ReplyView.as_view(), name='reply'),
    url(pgettext_lazy('postman_url', r'^view/(?P<message_id>[\d]+)/$'), MessageView.as_view(), name='view'),
    # Translators: 't' stands for 'thread'
    url(pgettext_lazy('postman_url', r'^view/t/(?P<thread_id>[\d]+)/$'), ConversationView.as_view(), name='view_conversation'),
    url(pgettext_lazy('postman_url', r'^archive/$'), ArchiveView.as_view(), name='archive'),
    url(pgettext_lazy('postman_url', r'^delete/$'), DeleteView.as_view(), name='delete'),
    url(pgettext_lazy('postman_url', r'^undelete/$'), UndeleteView.as_view(), name='undelete'),
    url(pgettext_lazy('postman_url', r'^mark-read/$'), MarkReadView.as_view(), name='mark-read'),
    url(pgettext_lazy('postman_url', r'^mark-unread/$'), MarkUnreadView.as_view(), name='mark-unread'),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('postman:inbox'), permanent=True)),
]

users/urls.py
from django.urls import path, include
from . import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [ 
    path('signup/', user_views.register, name = "signup"),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = 'logout'),
    path('profile/', user_views.profile, name='profile'),
    # path('password-reset/',
    #      auth_views.PasswordResetView.as_view(
    #          template_name='users/password_reset.html'
    #      ),
    #      name='password_reset'),
    # path('password-reset/done/',
    #      auth_views.PasswordResetDoneView.as_view(
    #          template_name='users/password_reset_done.html'
    #      ),
    #      name='password_reset_done'),
    # path('password-reset-confirm/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(
    #          template_name='users/password_reset_confirm.html'
    #      ),
    #      name='password_reset_confirm'),
    # path('password-reset-complete/',
    #      auth_views.PasswordResetCompleteView.as_view(
    #          template_name='users/password_reset_complete.html'
    #      ),
    #      name='password_reset_complete'),
]

categories/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from requests import get
import geoip2.database
from math import sin, cos, sqrt, atan2, radians
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length = 50)
    description = models.TextField()
    image = models.ImageField(upload_to='category_gallery')
    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "categories"

class Company(models.Model):
    name = models.CharField(max_length = 50)
    description = models.TextField()
    latitude = models.FloatField()
    longitude = models.FloatField()
    owner = models.ForeignKey(User, on_delete = models.CASCADE, related_name = "company_owner")
    category = models.ForeignKey(Category, on_delete = models.CASCADE)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "Companies"

    def get_absolute_url(self):
        return reverse('category_list')
		#if want to redirect to its detail page then
        # return reverse('company_detail' ,kwargs = {'pk' : self.pk})

    def get_distance(self):
        ip = get('https://api.ipify.org').text
        reader = geoip2.database.Reader('categories/GeoLite2-City.mmdb')
        response = reader.city(ip)
        current_lat = response.location.latitude
        current_lon = response.location.longitude
        comp_lat = self.latitude
        comp_lon = self.longitude
        R = 6373.0

        lat1 = radians(current_lat)
        lon1 = radians(current_lon)
        lat2 = radians(comp_lat)
        lon2 = radians(comp_lon)

        dlon = lon2 - lon1
        dlat = lat2 - lat1

        a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
        c = 2 * atan2(sqrt(a), sqrt(1 - a))

        distance = R * c
        return(distance)

    def orderby_distance(self):
        dicti = []
        for company in object.all():
            dist = company.get_distance()
            name = company.name
            dist_new = {
                'name' : name,
                'distance': dist,
            }
            dicti.append(dist_new)

        return dicti




class Product(models.Model):
    name = models.CharField(max_length = 50)
    company = models.ForeignKey(Company, on_delete= models.CASCADE)
    owner = models.ForeignKey(User, on_delete = models.CASCADE, related_name = "product_owner")

    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "Products"

class Comment(models.Model):
    text = models.TextField(max_length = 4000)
    company = models.ForeignKey(Company, on_delete= models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

categories/forms.py
from django import forms
from .models import Category, Comment

# class CompanyModelForm(forms.ModelForm):
# 	class Meta:
# 		model  = Category
# 		fields = ['name', 'description', 'category']

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['text',]

categories/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Company, Comment, Product
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView, TemplateView
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from . forms import CommentForm
from django.views.generic.edit import FormMixin

from requests import get
import geoip2.database
# Create your views here.
def home(request):
    return HttpResponse("<H1> Hello welcome to my page </H1>")

class CategoryList(ListView):
    model = Category
    context_object_name = 'companies'
    template_name = 'categories/category_list'
    paginate_by = 2

class CompanyList(ListView):
    model = Company
    context_object_name = 'companies'
    template_name = 'categories/company_list.html'


    def get_queryset(self):
        self.category = get_object_or_404(Category, name = self.kwargs['category'])
        return Company.objects.filter(category=self.category)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = self.category
        return context

    def orderby_distance(self):
        dicti = []
        for company in Company.object.all():
            dist = company.get_distance()
            name = company.name
            dist_new = {
                'name' : name,
                'distance': dist,
            }
            dicti.append(dist_new)

        return HttpResponse(dicti)


class CompanyCreateView(LoginRequiredMixin, CreateView):
    model = Company
    template_name = 'categories/company_create.html'
    fields = '__all__'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class CompanyUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Company
    template_name = 'categories/company_update.html'
    fields = ['name', 'description']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def test_func(self):
        company = self.get_object()
        if self.request.user == company.owner:
            return True
        return False


class CompanyDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Company
    template_name = 'categories/company_delete.html'
    success_url = '/categories'
    def test_func(self):
    	company = self.get_object()
    	if self.request.user == company.owner:
    		return True
    	return False

def search(request):
    company_list = Company.objects.all()
    company_filter = CompanyFilter(request.GET, queryset=company_list)
    return render(request, 'categories/company_search.html', {'filter': company_filter})


class CompanyDetailView(FormMixin, DetailView):
    model = Company
    template_name = 'categories/company_detail.html'
    form_class = CommentForm

    def get_success_url(self):
        #return reverse('categories/company_detail', kwargs={'category': self.object.category ,'pk':self.object.pk})
        return HttpResponseRedirect(self.request.path_info)

    def get_context_data(self, **kwargs):
        context = super(CompanyDetailView, self).get_context_data(**kwargs)
        context['form'] = CommentForm
        return context



    def form_valid(self, form):
        review = form.save(commit=False)
        review.created_by = self.request.user
        review.created_at = timezone.now()
        review.company = self.object.id
        review.save()
        return super(CompanyDetailView, self).form_valid(form)


def get_ip(request):
    ip = get('https://api.ipify.org').text
    reader = geoip2.database.Reader('categories/GeoLite2-City.mmdb')
    response = reader.city(ip)
    currrent_lat = response.location.latitude
    current_lon = response.location.longitude
    
    
    html = "<html><body> %s </body></html>" %ip
    return HttpResponse(html)

class ProductCreateView(CreateView):
    model=Product
    template_name='categories/product_new.html'
    fields=['name', 'company']



    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def test_func(self):
        company = self.get_object()
        if self.request.user == company.owner:
            return True
        return False



class AboutView(TemplateView):
    template_name = 'categories/aboutknowhere.html'

class AboutUsView(TemplateView):
    template_name = 'categories/aboutus.html' 

categories/templates/categories/aboutknowhere.html
{% extends 'categories/base.html' %}
{% block content %}

<style>
  .thumbnail {
    position: relative;
	}

	.caption {
	    position: absolute;
	    top: 15%;
	    left: 15%;
	    margin:auto;
        width:70%;        
	}
    .caption .content{
        color:	#2F4F4F;
        background:#EEEEEF;
        padding-top: 70px;
        padding-bottom:70px; 
    }
    .topcaption{
        position: absolute;
	    top: 2%;
	    left: 12%;
	    width: 65%;
        text-align:left;
        color:white;
    }	

</style>

<div class="row" id="box-search"  style="margin-top:-15px;">
    <div class="thumbnail text-center">
        <img src="/static/back.svg" width="100%" height="50%" alt="My image" class="img-responsive">
        <div class="topcaption">
            <h1>Knowhere</h1>
            <p>A place to find what you want</p>
        </div>
        <div class="caption">
                <img src="/static/back.jpg" width="100%" height="50%" alt="My image" class="img-responsive">
                <div class="content">
                    <h3>Knowhere directs u to your search.</h3>
                    <p>You can search for any company or product you want.<br>Lists the best options near you.</p>

                    

                </div>
        </div>
    </div>
</div>

{% endblock %}

categories/templates/categories/aboutus.html
<html>
<head>
</head>
<body>
about us
</body>
</html>

categories/templates/categories/category_list.html
{% extends 'categories/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<style>
  .thumbnail {
    position: relative;
	}

	.caption {
	    position: absolute;
	    top: 50%;
	    left: 35%;
	    width: 65%;
	}

	.containerimage {
	  position: relative;
		max-width: 800px; /* Maximum width */
	  margin: 0 auto; /* Center it */
		padding-left:20px;
	}

	.containerimage .content {
	  position: absolute; /* Position the background text */
	  bottom: 42px; /* At the bottom. Use top:0 to append it to the top */
	  background: rgb(0, 0, 0); /* Fallback color */
	  background: rgba(0, 0, 0, 0.8); /* Black background with 0.5 opacity */
	  color:black;
		width:200px;
		height:50px;
		text-align:center;
		padding-top:10px;
	}
	.container{
		margin:auto;
		max-width:900px;
	}

</style>
{% block navbar %}
{% endblock %}
<div class="row" id="box-search"  style="margin-top:-15px;">
    <div class="thumbnail text-center">
        <img src="/static/display.png" width="100%" alt="My image" class="img-responsive">
        <div class="caption">
          <form class="form-inline">
            <input class="form-control mr-lg-2 bg-transparent text-white col-md-3 col-sm-5 col-xs-12 pd05" type="search"
                placeholder="Search" aria-label="Search">
            <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
    </div>
</div>

<br>
<div class="container">
			<div class="row">
					{% for company in companies %}
						<div class="col-mx-1">
								<!-- {{company.description}} -->
								<div class="containerimage">
									<a href="{% url 'company_list' company.name %}">
										<img  src = "{{company.image.url}}" class="shadow mb-5 bg-white rounded" width="200" height="170">
									</a>
									<div class="content">
										<a href="{% url 'company_list' company.name %}">{{company.name}}</a>
									</div>
								</div>
							</div>

					{% endfor %}
			</div>
		</div>

	{% if is_paginated %}

	{% if page_obj.has_previous %}
	  <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
	  <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
	{% endif %}

	{% for num in page_obj.paginator.page_range %}
	  {% if page_obj.number == num %}
		<a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
	  {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
		<a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
	  {% endif %}
	{% endfor %}

	{% if page_obj.has_next %}
	  <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
	  <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
	{% endif %}

  {% endif %}
{% endblock %}

categories/templates/categories/company_create.html
{% extends 'categories/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<div class = "container" style="margin-left:250px; padding-right:350px;">
	    <form method = 'POST'>
				<h1><center>Create Your Company</center></h1>

	        {% csrf_token %}
	        {{form|crispy}}
	        <button type = "submit" value = "submit" class="btn btn-dark"> Create </button>
	    </form>
	</div>
{% endblock %}

categories/templates/categories/company_delete.html
{% extends 'categories/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<form method = 'POST'>
    	{% csrf_token %}
    	{{form|crispy}}
    	Do you want to delete {{object.name}}
    	<button type = "submit" class="btn btn-link"> Delete </button>
	</form>
{% endblock %}

categories/templates/categories/company_detail.html
{% extends 'categories/base.html' %}
{% load crispy_forms_tags %}
{% load comments %}
{% block content %}
<center><h3>{{object.name}}</h3></center>
		<style>

			 html,body{
				height: 90%;
				width: 100%;
				margin:auto;
			}
			#map {
				height:90%;
				width:50%;
				margin:auto;
			}
		</style>


	<div id="map" class="map"></div>
		<script>
		//var map = L.map('map').fitWorld();
			var map = L.map('map').setView([{{object.latitude}}, {{object.longitude }}], 10);
			L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
			maxZoom: 18,
			attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
			'<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
			'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
			id: 'mapbox.streets'
			}).addTo(map);
			function onLocationFound(e)
			{
				L.marker(e.latlng).addTo(map);
				showOnScreen(e.latlng.lat, e.latlng.lng);
				calculateDistance(e.latlng);
			}
			map.on('locationfound', onLocationFound);
			map.locate({ maxZoom: 16});
			function showOnScreen(long, lat)
			{
				document.getElementById('desc').innerHTML = long + ","+ lat;
			}
			function calculateDistance(e)
			{
				distr = e.distanceTo(L.latLng({{object.latitude}},{{object.longitude}}));
				document.getElementById('distr').innerHTML = distr;
			}
			var myIcon = L.icon(
				{
					iconUrl: 'https://image.flaticon.com/icons/svg/484/484167.svg',
					iconSize: [38, 95],
					iconAnchor: [22, 94],
					popupAnchor: [-3, -76],
					shadowUrl: '',
					shadowSize: [68, 95],
					shadowAnchor: [22, 94]
				});
			L.marker([{{object.latitude}}, {{object.longitude}}], {icon:myIcon}).addTo(map)
		.bindPopup("{{object.name}}").openPopup();


			map.on('click', function(e)
			{
				alert("Lat, Lon : " + e.latlng.lat + ", " + e.latlng.lng);
			});
			map.on('click', function(e)
			{
				var popLocation= e.latlng;
				var popup = L.popup()
				.setLatLng(popLocation)
				.setContent('you clicked here')
				.openOn(map);
			});
		</script>
	<div>

	<div id='{{ distr }}'></div> 
	<div id='desc'></div>

	<div id='distr' style="margin-left:200px;"></div>
	<div id='desc' style="margin-left:200px;"></div>


	</div>

	{% comment %} <div style="margin-left:200px;">
	<form method = "post">{% csrf_token %}
	{{form.as_p}}
	<button type = "submit" class="btn btn-dark">Post</button>
	</form>
	{% for comment in company.comment.all %}
		{{comment.text|linebreaks}}
	{% endfor %}
	</div>

	<div> {{ object.get_distance}}</div> {% endcomment %}


 {% comment %} this id for chat part {% endcomment %}
 <br>
<button class="btn btn-dark"style="margin-left:200px;;">
	<a href="{% url 'postman:write' object.owner %}" style="color:white;">write to {{ object.owner }}
	</a>
</button>
 <br>


{% get_comment_count for categories.company object_pk as comment_count %}
<p>{{ comment_count }} comments have been posted.</p>

{% render_comment_list for company %}

{% get_comment_list for categories.company object_pk as comment_list %}
{% for comment in comment_list %}
<p>Posted by: {{ comment.user_name }} on {{ comment.submit_date }}</p>
...
<p>Comment: {{ comment.comment }}</p>
...
{% endfor %}

{% comment %} {% render_comment_form for company %} {% endcomment %}


{% if user.is_authenticated %}
    {% get_comment_form for company as form %}
    <form action="{% comment_form_target %}" method="POST">
    {% csrf_token %}
    {{ form.comment }}

    {{ form.content_type }}
    {{ form.object_pk }}
    {{ form.timestamp }}
    {{ form.security_hash }}
    <input type="hidden" name="next" value="{% url 'aboutus' %}" />
    <input type="submit" value="Add comment" id="id_submit" />
    </form>
{% else %}
    <p>Please <a href="{% url 'login' %}">log in</a> to leave a comment.</p>
{% endif %}

{% endblock %}

categories/templates/categories/company_list.html
{% extends 'categories/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	{% for company in companies %}
		{% if company.category == category %}
	    <p>
	        <h1>{{ company.get_distance }}
	        	<a href="{% url 'company_detail'  company.category company.id %}">{{company.name}}</a> 
	        </h1>
		</p>
		{% endif %} 
	{% endfor %}  

{% endblock %}


 {% comment %} def orderby_distance(self):
        dicti = []
        for company in Company.object.all():
            dist = company.get_distance()
            name = company.name
            dist_new = {
                'name' : name,
                'distance': dist,
            }
            dicti.append(dist_new)

        return HttpResponse(dicti) {% endcomment %}

categories/templates/categories/company_update.html
{% extends 'categories/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<form method = 'POST'>
    	{% csrf_token %}
    	{{form|crispy}}
    <button type = "submit" value = "submit"> Update </button>
	</form>
{% endblock %}

categories/templates/categories/product_new.html
{% extends 'categories/base.html' %}
{% block content %}
<h1> New Product </h1>
<form action ="" method="post">{% csrf_token %}
{{ form.as_p }}
<input type ="submit" value="Save" />
</form>
{% endblock %}